-- Tabla para desplegable TipoDocumento
CREATE TABLE MELANBIDE11_DESP_TIPODOCUMENTO (
    ID INTEGER NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ACTIVO VARCHAR(1) DEFAULT 'S',
    ORDEN INTEGER DEFAULT 0,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MELANBIDE11_DESP_TIPODOCUMENTO PRIMARY KEY (ID),
    CONSTRAINT UK_MELANBIDE11_DESP_TIPODOCUMENTO_CODIGO UNIQUE (CODIGO)
);

-- Secuencia para IDs
CREATE SEQUENCE SEQ_MELANBIDE11_DESP_TIPODOCUMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Datos de ejemplo
INSERT INTO MELANBIDE11_DESP_TIPODOCUMENTO (ID, CODIGO, DESCRIPCION, ACTIVO, ORDEN) VALUES 
    (SEQ_MELANBIDE11_DESP_TIPODOCUMENTO.NEXTVAL, 'OPC1', 'Opción 1', 'S', 1);
INSERT INTO MELANBIDE11_DESP_TIPODOCUMENTO (ID, CODIGO, DESCRIPCION, ACTIVO, ORDEN) VALUES 
    (SEQ_MELANBIDE11_DESP_TIPODOCUMENTO.NEXTVAL, 'OPC2', 'Opción 2', 'S', 2);
INSERT INTO MELANBIDE11_DESP_TIPODOCUMENTO (ID, CODIGO, DESCRIPCION, ACTIVO, ORDEN) VALUES 
    (SEQ_MELANBIDE11_DESP_TIPODOCUMENTO.NEXTVAL, 'OPC3', 'Opción 3', 'S', 3);
