-- Script de creación de tabla MELANBIDE11_DESGRSB
-- Desglose de Retribución Salarial Bruta

-- Crear tabla
CREATE TABLE MELANBIDE11_DESGRSB (
  ID            NUMBER NOT NULL,
  NUMEXP        VARCHAR2(50) NOT NULL,
  DNICONTRSB    VARCHAR2(15) NOT NULL,
  RSBTIPO       VARCHAR2(1) NOT NULL,     -- "1"=complemento salarial, "2"=percepción extrasalarial
  RSBIMPORTE    NUMBER(8,2) NOT NULL,
  RSBCONCEPTO   VARCHAR2(10),             -- "F"=Fijo, "V"=Variable, "FIJO", "VARIABLE", "FINKOA"
  RSBOBSERV     VARCHAR2(500),
  CONSTRAINT PK_MELANBIDE11_DESGRSB PRIMARY KEY (ID)
);

-- Crear secuencia para IDs
CREATE SEQUENCE SEQ_MELANBIDE11_DESGRSB START WITH 1 INCREMENT BY 1 NOCACHE;

-- Añadir comentarios
COMMENT ON TABLE MELANBIDE11_DESGRSB IS 'Desglose de retribución salarial bruta - complementos y percepciones';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.ID IS 'Identificador único de la línea';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.NUMEXP IS 'Número de expediente';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.DNICONTRSB IS 'DNI/NIE de la persona contratada';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.RSBTIPO IS 'Tipo: 1=Complemento salarial, 2=Percepción extrasalarial';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.RSBIMPORTE IS 'Importe en euros';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.RSBCONCEPTO IS 'Concepto: F=Fijo, V=Variable, FIJO, VARIABLE, FINKOA';
COMMENT ON COLUMN MELANBIDE11_DESGRSB.RSBOBSERV IS 'Observaciones adicionales';

-- Crear índices
CREATE INDEX IDX_DESGRSB_NUMEXP ON MELANBIDE11_DESGRSB(NUMEXP);
CREATE INDEX IDX_DESGRSB_DNI ON MELANBIDE11_DESGRSB(DNICONTRSB);
CREATE INDEX IDX_DESGRSB_TIPO ON MELANBIDE11_DESGRSB(RSBTIPO);

-- Script de actualización de tabla MELANBIDE11_CONTRATACION
-- Añadir campos calculados para desglose RSB (si no existen)

-- Verificar si las columnas ya existen antes de añadirlas
-- En Oracle, si la columna ya existe, dará error. Ejecutar individualmente según necesidad.

ALTER TABLE MELANBIDE11_CONTRATACION ADD RSBSALBASE NUMBER(8,2);
ALTER TABLE MELANBIDE11_CONTRATACION ADD RSBPAGASEXTRA NUMBER(8,2);
ALTER TABLE MELANBIDE11_CONTRATACION ADD RSBCOMPIMPORTE NUMBER(8,2);
ALTER TABLE MELANBIDE11_CONTRATACION ADD RSBCOMPEXTRA NUMBER(8,2);
ALTER TABLE MELANBIDE11_CONTRATACION ADD RSBCOMPCONV NUMBER(8,2);

-- Añadir comentarios a las nuevas columnas
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RSBSALBASE IS 'Salario base anual';
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RSBPAGASEXTRA IS 'Pagas extraordinarias anuales';
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RSBCOMPIMPORTE IS 'Total complementos salariales (fijos + variables)';
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RSBCOMPEXTRA IS 'Total percepciones extrasalariales';
COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RSBCOMPCONV IS 'Retribución salarial bruta computable del convenio (calculado: base + pagas + fijos)';

-- Verificar la creación
SELECT COUNT(*) FROM MELANBIDE11_DESGRSB;
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MELANBIDE11_CONTRATACION' AND COLUMN_NAME LIKE 'RSB%';
