--------------------------------------------------------
--  DDL for Table MELANBIDE11_DESGLOSE_RSB
--  Tabla para almacenar el desglose de Retribución Salarial Bruta
--------------------------------------------------------
CREATE TABLE MELANBIDE11_DESGLOSE_RSB 
(	
    ID NUMBER(10,0), 
    NUM_EXP VARCHAR2(30 BYTE), 
    DNI VARCHAR2(15 BYTE),
    TIPO NUMBER(1,0),
    IMPORTE NUMBER(10,2), 
    CONCEPTO VARCHAR2(1 BYTE),
    OBSERVACIONES VARCHAR2(500 BYTE)
);

COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.ID IS 'Id secuencial';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.NUM_EXP IS 'Número de Expediente';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.DNI IS 'DNI/NIE de la persona contratada';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.TIPO IS 'Tipo: 1=Complementos salariales, 2=Otras percepciones';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.IMPORTE IS 'Importe del concepto';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.CONCEPTO IS 'Concepto: F=Fijo, V=Variable';
COMMENT ON COLUMN MELANBIDE11_DESGLOSE_RSB.OBSERVACIONES IS 'Observaciones del concepto';

--------------------------------------------------------
--  DDL for Index MELANBIDE11_DESGLOSE_RSB_PK
--------------------------------------------------------
CREATE UNIQUE INDEX MELANBIDE11_DESGLOSE_RSB_PK ON MELANBIDE11_DESGLOSE_RSB (ID);

--------------------------------------------------------
--  Constraints for Table MELANBIDE11_DESGLOSE_RSB
--------------------------------------------------------
ALTER TABLE MELANBIDE11_DESGLOSE_RSB ADD CONSTRAINT MELANBIDE11_DESGLOSE_RSB_PK PRIMARY KEY (ID) USING INDEX ENABLE;
ALTER TABLE MELANBIDE11_DESGLOSE_RSB MODIFY (ID NOT NULL ENABLE);
ALTER TABLE MELANBIDE11_DESGLOSE_RSB MODIFY (NUM_EXP NOT NULL ENABLE);
ALTER TABLE MELANBIDE11_DESGLOSE_RSB MODIFY (DNI NOT NULL ENABLE);
ALTER TABLE MELANBIDE11_DESGLOSE_RSB MODIFY (TIPO NOT NULL ENABLE);
ALTER TABLE MELANBIDE11_DESGLOSE_RSB MODIFY (IMPORTE NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Sequence SEQ_MELANBIDE11_DESGLOSE_RSB
--------------------------------------------------------
CREATE SEQUENCE SEQ_MELANBIDE11_DESGLOSE_RSB MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

--------------------------------------------------------
--  Script para añadir nuevos campos a MELANBIDE11_CONTRATACION
--  (solo ejecutar si no existen ya)
--------------------------------------------------------
-- ALTER TABLE MELANBIDE11_CONTRATACION ADD SALARIO_BASE NUMBER(10,2);
-- ALTER TABLE MELANBIDE11_CONTRATACION ADD PAGAS_EXTRAORD NUMBER(10,2);
-- ALTER TABLE MELANBIDE11_CONTRATACION ADD RETRIB_COMPUTABLE NUMBER(10,2);

-- COMMENT ON COLUMN MELANBIDE11_CONTRATACION.SALARIO_BASE IS 'Salario base anual';
-- COMMENT ON COLUMN MELANBIDE11_CONTRATACION.PAGAS_EXTRAORD IS 'Pagas extraordinarias anuales';
-- COMMENT ON COLUMN MELANBIDE11_CONTRATACION.RETRIB_COMPUTABLE IS 'Retribución computable para la convocatoria';
